project_id = "yutddrrtogmpakzfzaqz"

[functions.create-checkout-link]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.save-config]
verify_jwt = false

[functions.delete-checkout-link]
verify_jwt = false