project_id = "yutddrrtogmpakzfzaqz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.create-checkout-link]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.save-config]
verify_jwt = false

[functions.delete-checkout-link]
verify_jwt = false

[functions.process-transparent-payment]
verify_jwt = false

[functions.save-checkout-customization]
verify_jwt = false