// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yutddrrtogmpakzfzaqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1dGRkcnJ0b2dtcGFremZ6YXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjQwNjEsImV4cCI6MjA2ODc0MDA2MX0.VGGRkeibv2HzjoFQJ_afAgrt7QSKhCdjmlC2-gEcvE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});